import { defaultCourseConfig, type CustomCourseConfig } from "./CourseCodec";

function preset(overrides: Partial<CustomCourseConfig>): CustomCourseConfig {
  return { ...defaultCourseConfig(), ...overrides };
}

export const COURSE_PRESETS: { label: string; config: CustomCourseConfig }[] = [
  {
    label: "THE CHUTE",
    config: preset({
      name: "The Chute",
      length: 800,
      steepness: 0.22,
      waypoints: [
        { z: 0, x: 0, width: 18 },
        { z: 0.2, x: 2, width: 16 },
        { z: 0.4, x: -3, width: 15 },
        { z: 0.6, x: 1, width: 16 },
        { z: 0.8, x: -2, width: 17 },
        { z: 1.0, x: 0, width: 18 },
      ],
      treeDensity: 0.8,
      obstacleDensity: 0.7,
      jumps: [{ z: 0.5 }],
      coinCount: 15,
      roughness: 0.7,
      atmospherePreset: "midday",
      seed: 101,
    }),
  },
  {
    label: "POWDER PARADISE",
    config: preset({
      name: "Powder Paradise",
      length: 1800,
      steepness: 0.10,
      waypoints: [
        { z: 0, x: 0, width: 35 },
        { z: 0.15, x: 8, width: 32 },
        { z: 0.3, x: -5, width: 38 },
        { z: 0.5, x: 10, width: 35 },
        { z: 0.65, x: -8, width: 30 },
        { z: 0.8, x: 3, width: 35 },
        { z: 1.0, x: 0, width: 35 },
      ],
      treeDensity: 0.3,
      obstacleDensity: 0.2,
      jumps: [{ z: 0.3 }, { z: 0.6 }],
      coinCount: 40,
      roughness: 0.3,
      atmospherePreset: "morning",
      seed: 202,
    }),
  },
  {
    label: "MOGUL MADNESS",
    config: preset({
      name: "Mogul Madness",
      length: 600,
      steepness: 0.18,
      mogulIntensity: 0.9,
      courseType: "moguls",
      jumps: [{ z: 0.3 }, { z: 0.7 }],
      coinCount: 20,
      roughness: 0.8,
      treeDensity: 0.4,
      obstacleDensity: 0.3,
      atmospherePreset: "midday",
      seed: 303,
    }),
  },
  {
    label: "JUMP LINE",
    config: preset({
      name: "Jump Line",
      length: 1200,
      steepness: 0.14,
      courseType: "terrainPark",
      jumps: [
        { z: 0.1 }, { z: 0.2 }, { z: 0.3 }, { z: 0.4 }, { z: 0.5 },
        { z: 0.6 }, { z: 0.7 }, { z: 0.8 }, { z: 0.9 },
      ],
      coinCount: 30,
      treeDensity: 0.2,
      obstacleDensity: 0.1,
      atmospherePreset: "midday",
      seed: 404,
    }),
  },
  {
    label: "SLALOM SPRINT",
    config: preset({
      name: "Slalom Sprint",
      length: 1000,
      steepness: 0.16,
      courseType: "slalom",
      jumps: [],
      coinCount: 20,
      treeDensity: 0.3,
      obstacleDensity: 0.2,
      roughness: 0.4,
      atmospherePreset: "morning",
      seed: 505,
    }),
  },
  {
    label: "NIGHT RIDER",
    config: preset({
      name: "Night Rider",
      length: 1200,
      steepness: 0.13,
      atmospherePreset: "night",
      snowIntensity: 1.5,
      fogDensity: 0.7,
      jumps: [{ z: 0.3 }, { z: 0.6 }],
      coinCount: 25,
      treeDensity: 0.5,
      obstacleDensity: 0.4,
      seed: 606,
    }),
  },
  {
    label: "THE GAUNTLET",
    config: preset({
      name: "The Gauntlet",
      length: 2400,
      steepness: 0.20,
      waypoints: [
        { z: 0, x: 0, width: 25 },
        { z: 0.1, x: 5, width: 20 },
        { z: 0.2, x: -8, width: 18 },
        { z: 0.3, x: 10, width: 16 },
        { z: 0.4, x: -6, width: 20 },
        { z: 0.5, x: 3, width: 22 },
        { z: 0.6, x: -10, width: 18 },
        { z: 0.7, x: 8, width: 16 },
        { z: 0.8, x: -3, width: 20 },
        { z: 0.9, x: 5, width: 22 },
        { z: 1.0, x: 0, width: 25 },
      ],
      obstacleDensity: 0.9,
      treeDensity: 0.8,
      jumps: [{ z: 0.2 }, { z: 0.5 }, { z: 0.8 }],
      coinCount: 35,
      roughness: 0.8,
      atmospherePreset: "sunset",
      seed: 707,
    }),
  },
  {
    label: "HALF-PIPE HEAVEN",
    config: preset({
      name: "Half-Pipe Heaven",
      length: 1000,
      steepness: 0.12,
      courseType: "halfPipe",
      halfPipe: { startZ: 0.1, endZ: 0.9, width: 24, depth: 7 },
      jumps: [],
      coinCount: 20,
      treeDensity: 0.1,
      obstacleDensity: 0.0,
      roughness: 0.2,
      atmospherePreset: "midday",
      snowIntensity: 0.5,
      seed: 808,
    }),
  },
];
